@startuml

left to right direction
skinparam componentStyle uml2
skinparam monochrome true

[POS Application] as pos
[WebShop] as web

[OrderFulfillmentDirector] as facade

actor "Web Customer" as customer
customer -down-> web
web -down-> facade

actor "Store Manager" as manager
manager -down-> pos
pos -down-> facade

[PaymentProvider] as payment
[ProductionProvider] as production
[BillingProvider] as billing

facade -down-> payment
facade -down-> production
facade -down-> billing

@enduml
